from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from typing import Dict, Any

class PDFService:
    def generate_profile_pdf(self, profile_data: Dict[str, Any]) -> BytesIO:
        """
        Generates a professional PDF document from the user's profile data.
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4)
        styles = getSampleStyleSheet()
        
        # Custom Title Style
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.blue,
            alignment=1, # Center
            spaceAfter=20
        )
        
        elements = []
        
        # Header
        elements.append(Paragraph("PaperAmbulance - Universal Profile", title_style))
        elements.append(Paragraph("This document contains your verified digital profile for form submission.", styles['Normal']))
        elements.append(Spacer(1, 20))
        
        # Data Table
        data = [["Field", "Stored Information"]]
        for key, value in profile_data.items():
            # Standardize key names for display
            display_key = key.replace('_', ' ').title()
            data.append([display_key, str(value)])
            
        table = Table(data, colWidths=[150, 300])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        
        elements.append(table)
        elements.append(Spacer(1, 40))
        
        # Footer
        footer_text = "Generated by PaperAmbulance AI Assistant. Always verify data before official submission."
        elements.append(Paragraph(footer_text, styles['Italic']))
        
        doc.build(elements)
        buffer.seek(0)
        return buffer

pdf_service = PDFService()
